apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: srcmongodb-kube-service-bindings-examples
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: srcmongodb-kube-service-bindings-examples
    app.kubernetes.io/part-of: kube-service-bindings-examples
  name: srcmongodb-kube-service-bindings-examples
spec:
  replicas: 0
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: nodejs-app
      app.kubernetes.io/instance: srcmongodb-kube-service-bindings-examples
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nodejs-app
        app.kubernetes.io/instance: srcmongodb-kube-service-bindings-examples
    spec:
      containers:
      - image: quay.io/redhat-user-workloads-stage/cpapasta-tenant/kube-service-bindings-examples/srcmongodb-kube-service-bindings-examples@sha256:166a12df2acb684ddd13b17403fd0e0295c6f3a910341d73cdf12cc4c63c1d44
        name: my-nodejs
        ports:
        - containerPort: 3001
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 10m
            memory: 50Mi
status: {}
