apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: srcmongodb-kube-service-bindings-examples
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: srcmongodb-kube-service-bindings-examples
    app.kubernetes.io/part-of: kube-service-bindings-examples
  name: srcmongodb-kube-service-bindings-examples
spec:
  ports:
  - name: "3001"
    port: 3001
    targetPort: 3001
  selector:
    app.kubernetes.io/instance: srcmongodb-kube-service-bindings-examples
status:
  loadBalancer: {}
