apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: srcmongodb-kube-service-bindings-examples
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-user-workloads-stage/cpapasta-tenant/kube-service-bindings-examples/srcmongodb-kube-service-bindings-examples@sha256:166a12df2acb684ddd13b17403fd0e0295c6f3a910341d73cdf12cc4c63c1d44
        name: my-nodejs
        resources: {}
status: {}
