apiVersion: route.openshift.io/v1
kind: Route
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: srcmongodb-kube-service-bindings-examples
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: srcmongodb-kube-service-bindings-examples
    app.kubernetes.io/part-of: kube-service-bindings-examples
  name: srcmongodb-kube-service-bdmgr
spec:
  path: /
  port:
    targetPort: 3001
  to:
    kind: Service
    name: srcmongodb-kube-service-bindings-examples
    weight: null
status: {}
